// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { DbVector2 as __DbVector2 } from "./db_vector_2_type";

export type Circle = {
  entityId: number,
  playerId: number,
  direction: __DbVector2,
  speed: number,
  lastSplitTime: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Circle {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("entityId", AlgebraicType.createU32Type()),
      new ProductTypeElement("playerId", AlgebraicType.createU32Type()),
      new ProductTypeElement("direction", __DbVector2.getTypeScriptAlgebraicType()),
      new ProductTypeElement("speed", AlgebraicType.createF32Type()),
      new ProductTypeElement("lastSplitTime", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Circle): void {
    Circle.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Circle {
    return Circle.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


